# Generated by Django 5.2.6 on 2025-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_point_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, db_index=True),
        ),
    ]



